### ISSUE TITLE
如何把libtorch训练好的模型通过jit/onnx/tensorrt方法之一进行预测

### ISSUE THREAD

**Issue by ximitiejiang** [thisisi3/libtorch-faster-rcnn#1]
你好，看到你实施的libtorch-fasterrcnn非常完整，我刚刚开始测试libtorch但发现一个问题：
我可以在libtorch c++中构建模型并完成整个训练，然后重新通过libtorch加载完成推理，整个过程跟你实现的train.cpp、test.cpp一致。但在部署时我把训练好的pt模型(这个模型应该属于torchscript模型)，重新在另一个c++文件中通过torch::jit::load()加载进来，然后在推理这句却报错，如下是代码
`torch::jit::Module model = torch::jit::load("model.pt");`
`auto output = model.forward({ input_tensor.to(device) }).toTensor();`

该pt模型如果反过来在python中通过torch.jit.load()也是一样的报错，报错信息是AttributeError: 'RecursiveScriptModule' object has no attribute 'forward'，貌似经过libtorch训练然后torch::save()之后的模型虽然也是torchscript模型，但仅保存了权重却没有保存相关模型结构，跟python里边jit.trace导出的torchscript模型并不一样，所以没法找到forward函数来进行推理。不知道你有没有基于你的libtorch模型进行部署测试，是否也有这种问题？
或者有其他什么方式可以把libtorch训练得到的pt模型进行转换得到onnx模型做部署？

**Comment by thisisi3** [comment]
@ximitiejiang 
是的，保存的model.pt只是权重，并没有模型结构。部署端必须有模型结构的实现才能加载model.pt来完成部署。转成onnx可能是一个方法，但是我这方面经验有限无法帮到你，抱歉。

**Comment by ximitiejiang** [comment]
thanks
